### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by mazenR** [kosciukiewicz/sbc-solver#3]
the ui is there but no players are getting imported nor sbc

**Comment by kosciukiewicz** [comment]
I assume You are trying to use the solver in the EA FC **25** Web App (as any other is not available right now). Be aware that solver does not support freshly released version of the game. I need some time to adapt it and I plan to release it in the middle of next week! 🤞

**Comment by mazenR** [comment]
thank you hope you finsh it soon :)

**Comment by kosciukiewicz** [comment]
New release: https://github.com/kosciukiewicz/sbc-solver/releases/tag/25.1.0. Have fun!

**Comment by mazenR** [comment]
works!! thank you
